### ISSUE TITLE
Use configure_me to configure the service?

### ISSUE THREAD

**Issue by Kixunil** [Podcastindex-org/helipad#10]
It'd be great to use [`configure_me`](https://docs.rs/configure_me/latest/configure_me/) to handle the configuration. It was designed mainly for long-running services like this one. It can:

* Read configuration from files, env vars and CLI args
* Parse the configuration into more appropriate types, reporting nice error messages to the user
* Generate help and man pages
* Support all GNU styles of arguments I know of
* Read from directories to allow composable configuration
* Avoid boilerplate thanks to declarative syntax

I can help with integration if needed.

**Comment by daveajones** [comment]
Thanks.  I haven't used it before.  Looks like a good package.  I'll put this on the to-do list.

**Comment by daveajones** [comment]
Read up on this crate. I really like it.  I’ll work to switch over to it.

**Comment by daveajones** [comment]
Using this method in v0.1.5 release.
