### ISSUE TITLE
Allow explicit config of paths

### ISSUE THREAD

**Issue by Kukks** [Podcastindex-org/helipad#16]
You currently require that LND's macaroon and cert are in a specific path(s). In BTCPay, we have them elsewhere which makes it impossible to integrate helipad (https://github.com/btcpayserver/btcpayserver-docker/pull/567). I opened a PR with the required changes but I don't have a rust IDE and don't know its syntax to finish the PR. https://github.com/Podcastindex-org/helipad/pull/8

Ideally, `LND_ADMINMACAROON` and `LND_TLSCERT` environment variables would take precedence if set, and helipad would attempt them first.

**Comment by Kukks** [comment]
Ah, this is a duplicate of #5

**Comment by daveajones** [comment]
I’m fixing this right now. The new behavior will be that env variables take precedence over everything, then a config file will be read that specifies the various paths wanted, then finally a set of sane fallbacks will be used. These changes will be in the next release.
