### ISSUE TITLE
Cannot read admin macaroon 

### ISSUE THREAD

**Issue by Kukks** [Podcastindex-org/helipad#19]
Using: Docker image podcastindexorg/podcasting20-helipad:v0.1.6

I am setting `LND_ADMINMACAROON` to "/lnd/admin.macaroon". I have verified the file exists manually. However, helipad reports it cannot find the file.

Fix:  adding ` user: "root"` to the docker compose service makes it able to read the file

**Comment by Kukks** [comment]
> Not an issue on raspiblitz https://github.com/SpencerPearson/helipad-for-raspiblitz/blob/master/bonus.helipad.sh#L154

This is specific to docker image usage.

**Comment by ericpp** [comment]
Closing this issue for now, but let me know if you're still having trouble with it. I'm guessing that your admin.macaroon permissions were root-only which prevented docker from reading the file.
