### ISSUE TITLE
Allow specifying subpath

### ISSUE THREAD

**Issue by Kukks** [Podcastindex-org/helipad#20]
Currently, the website expects that you are running at the base url path "/". In BTCPay, we run helipad under `/helipad` though. This results in nothing being able to load (styles and js and any js calls)

quick fix I did was some ugly hardcoded rewriting rules in nginx: https://github.com/btcpayserver/btcpayserver-docker/pull/567/files#diff-05200e2a470c28b099494cd0a09359a967606b7768dd50eaa6d83bfb72b68979

**Comment by daveajones** [comment]
Hmm.  Let me get a fix in for this on the next go around.

**Comment by valcanobacon** [comment]
This is how its currently handled with raspiblitz https://github.com/SpencerPearson/helipad-for-raspiblitz/blob/master/bonus.helipad.sh#L147

**Comment by ericpp** [comment]
I think 8a9843d435501089fc4169f5ddf4d33ee6aad468 should fix the issue now. I've changed the absolute paths into relative paths as a part of that change.
