### ISSUE TITLE
Configurable notification sound 

### ISSUE THREAD

**Issue by valcanobacon** [Podcastindex-org/helipad#21]
Currently the only way to change the notification is replace the sound file after installation. I propose the file path be configurable via an environment variable and config file. Additionally, it would be nice to make it configurable via the Web UI.

**Comment by SpencerPearson** [comment]
I'm sure we want to crawl before we walk, but having several customizable sounds at certain amounts (like the row of ducks boost if 2222 or 22222 etc comes in, as an extreme example) I think should be an option to aim for long-term, as well as a silence option for boosts below a certain amount and maybe a range trigger for anything not specified (for example the Moe Facts "baller" jingle at anything 50k+, and a pew for anything between the silence maximum and the baller minimum)

Just my 2 sats 😉
