### ISSUE TITLE
Add a configurable minumum Boost amount 

### ISSUE THREAD

**Issue by valcanobacon** [Podcastindex-org/helipad#22]
Currently, I can send a large amount of small boosts which would cause a mess to scroll through as well the notification sound to be played an obnoxious amount of times. A 1000 boosts each 1 sat is not very expensive. If we had a configurable minimum amount the user could make the price of boost and/or notification too expensive to be spamy. I think this would be configurable via environmental variables and the configuration file. Configuration via the web ui should also be considered.

**Comment by SpencerPearson** [comment]
A lot of these admin-type features might call for some sort of settings dashboard in the long term.

**Comment by daveajones** [comment]
Yeah I hope to not have to do that for a while.

**Comment by SpencerPearson** [comment]
> Yeah I hope to not have to do that for a while.

Hopefully between a few of us just dipping our toes in right now we can offload all of these frond end/UX concerns so you don't have to do everything every time <3

I hope I don't sound like I'm featurebegging in these posts, just trying to brainstorm stuff. Anything I suggest isn't with the expectation that someone else comes along and does it. I just need to play with some stuff and work up to it.

You have given us so much, Dave! We wanna give back.

**Comment by daveajones** [comment]
Not at all Spencer. All good brother. 🙏

**Comment by valcanobacon** [comment]
> Yeah I hope to not have to do that for a while.

Then lets not and implement the settings without changes to the UI.

I am not sure what configuration on umbrel looks like but people on Raspiblitz are willing to ssh in and edit the configuration file and restart the service.
