### ISSUE TITLE
CORS permissions on JSON feeds - relax?

### ISSUE THREAD

**Issue by jamescridland** [Podcastindex-org/helipad#26]
The JSON feed of /boosts (and /streams when that one comes) currently has standard (if restrictive) CORS settings.

My use-case is that I'd quite like to be able to have a method of pulling my boost messages off my Umbrel and publishing them on the web. My initial thought was to just have a JavaScript page that works internally in my network, that would read the boosts JSON and post them to an API on my public server; but I'm foiled by the CORS policy.

It would be good - and I think without any security issue, given that this page is only viewable on a local network (but that's up to you) - if the [CORS policy was open for these JSON feeds](https://www.w3.org/wiki/CORS_Enabled).

It's a case of adding the following header, below.

```
Access-Control-Allow-Origin: *
```

**Comment by daveajones** [comment]
This might need preflight as well.

**Comment by valcanobacon** [comment]
Could this be configurable?

**Comment by daveajones** [comment]
> Could this be configurable?

What do you mean?

**Comment by valcanobacon** [comment]
An environment variable for the right side of header so whoever hosts the service can specify the value. None/null means don't include the header and you can set the default to `localhost` or `*`.

**Comment by daveajones** [comment]
Ah, I see. Sure that can be done.

**Comment by daveajones** [comment]
All endpoints will be CORS enabled in v0.1.9
