### ISSUE TITLE
Use `tokio::time::sleep` instead of `std::thread::sleep`?

### ISSUE THREAD

**Issue by ericpp** [Podcastindex-org/helipad#47]
The `std::thread::sleep` call in the LND poller seems to cause the HTTP server to sleep as well (at least in my copy of Helipad). This causes the web interface to feel sluggish as the browser is waiting for the HTTP server to stop sleeping.

Changing the following line:

https://github.com/Podcastindex-org/helipad/blob/973b847074e281fbebe3640f93ae5f590a891a94/src/main.rs#L601

to use `tokio::time::sleep` seems to fix the issue:

```rust
tokio::time::sleep(tokio::time::Duration::from_millis(9000)).await;
```

**Comment by daveajones** [comment]
Good catch! I’ll make that change. I’ve been wondering why that’s happening.
