### ISSUE TITLE
Allow different paths to be set via env variables

### ISSUE THREAD

**Issue by SpencerPearson** [Podcastindex-org/helipad#5]
This current release was built with the Umbrel environment in mind. For implementation in other environments (I'm currently looking to build this as a Raspiblitz Additional Service), we need to be able to change relevant paths.

For example, the SQLite database needs to be saved at /mnt/hdd/app-data/helipad in Raspiblitz

Related, we need to be able to point to /home/helipad/.lnd as the root of the path to look for the tls.cert and the macaroon.

**Comment by daveajones** [comment]
In general, it seems that the configuration needs to be more flexible.  If #10 can help with that, then maybe we can kill all of these birds with one stone.
