### ISSUE TITLE
Using helipad on btcpayserver docker?

### ISSUE THREAD

**Issue by yaeloss** [Podcastindex-org/helipad#51]
I'm wondering if anyone has been able to configure helipad for use on a btcpayserver docker, which runs an internal LND node.

Helipad works great on Umbrel, but I'd love to also be able to use it for other projects and podcasts that receive sats on a cloud node, specifically for those who have Voltage, Lunanode, or other LND or BTCPay Server instances.

At present, it seems there isn't a good way to read boostagrams compiled from all sources (fountain, breez, castamatic, podverse, etc.), unless you're using an Umbrel node. I know Fountain has discussed compiling all boostagrams in the next update, but it'd be excellent to make use of the Helipad UI for use on docker instances.

**Comment by yaeloss** [comment]
From what I've seen other podcasters do, there is a small split via [http://podcasterwallet.com](url) they'll send to an Umbrel node running Helipad. Not a bad fix at the moment.

**Comment by daveajones** [comment]
You can run it from anywhere Yael.  You can run it on your own laptop as long as you can point it at the LND node's REST port.  That's the only requirement.  To run it that way you can download the source and compile it, then configure the helipad.conf file to point to the right place.

On the next release I can also create a generic, non-umbrel docker that is more easily configurable without having to compile from source.

**Comment by daveajones** [comment]
I meant GRPC port, not REST.

**Comment by yaeloss** [comment]
Okay, perfect. I will give this a shot. I know I've been bugging the Mastodon with this question for a while, but now I understand better!
