### ISSUE TITLE
Unicode/UTF-8 export in the .csv file

### ISSUE THREAD

**Issue by yaeloss** [Podcastindex-org/helipad#55]
When a user exports the CSV file from the Helipad screen, the output file does not use unicode UTF-8, but rather ASCII.

That means when users send a boostagram with emojis, or non-English languages with accents (think Yaël or ☺), those characters show up as an error.

I'm unsure what the change would be, but perhaps in the CSV file generation to select for full UTF-8 rather than ASCII.

Those characters work great on Helipad, but just don't show correctly once you export to CSV.

**Comment by daveajones** [comment]
Interesting. Will investigate this.

**Comment by ericpp** [comment]
@yaeloss Which operating system and program are you using to open the CSV file? I did a quick test and "😊😊think Yaël or ☺" seemed to export fine from Helipad to LibreOffice 7 on Windows 10.

**Comment by yaeloss** [comment]
I was using Excel on Windows and libreoffice on Linux. 

However, it seems it got fixed. Either my side or via an update. Regardless, settled! Thank you for investigating.
