### ISSUE TITLE
is the docker version older than this repo?

### ISSUE THREAD

**Issue by DaveHamilton** [Podcastindex-org/helipad#56]
I pulled down `podcastindexorg/helipad:latest` first, just to test this, but it seems to not matter.

Github says the latest version is 0.1.10
The lower right corner of the helipad web interface says 0.1.7
The Title tag of the helipad web interface says 0.1.5

Is there a way to tell if I'm running the latest version? And if I'm not running the latest version, how do I update so that I am?

Thanks!

<img width="170" alt="image" src="https://user-images.githubusercontent.com/1993106/231594271-c343a3c8-d180-4306-ad99-9d5739a92326.png">

**Comment by daveajones** [comment]
We don’t have an automated docker build pipeline for Helipad so the docker image will lag primarily until I release a new version targeted for Umbrel which I haven’t done in a bit.  If you want the latest code then it should be here if you clone the repo. I’ll check on the title vs html version mismatch. I guess that’s a bug.
