### ISSUE TITLE
For security, require readonly.macaroon rather than admin?

### ISSUE THREAD

**Issue by SpencerPearson** [Podcastindex-org/helipad#6]
It seems that for full functionality (at least currently?) helipad would only need a readonly macaroon rather than full admin macaroon

**Comment by Kixunil** [comment]
The full path should be configurable and then this tool wouldn't even have to care. The user can then set readonly or invoice - whichever is actually needed.

**Comment by daveajones** [comment]
Yes, making this configurable is the right way to go.

**Comment by daveajones** [comment]
Fixed in v0.1.5 release by providing a configurable path through the environment and a config file.
