### ISSUE TITLE
StartOS no longer has Helipad

### ISSUE THREAD

**Issue by adamc199** [Podcastindex-org/helipad#65]
Got a ping from Matt at Start9 and he says that Helipad was never officially submitted and now it's no longer in the marketplace
It is still installed on mine, but I'm not getting code updates of course.

Can it be resubmitted to StartOS?

**Comment by ericpp** [comment]
I was working on getting a common Docker image going that could be used for both Umbrel and StartOS before submitting it to the StartOS marketplace. StartOS doesn't use Docker to run its operating system (unlike Umbrel), but it does use Docker to run third party apps.

The version of Helipad that you're using is one that I custom compiled and had you download and sideload onto your device. I do have an updated version of that here, if you want to sideload a new version: https://github.com/ericpp/helipad-startos/releases

If @daveajones has set up the Docker Hub credentials in GitHub, pushing out a new Docker image should be as simple as going to the `Actions` tab in GitHub, clicking on `Docker Image CI`, and clicking on the `Run Workflow` button. I can then update my repo to point to the image, have Dave pull in the changes to the [podcastindex fork](https://github.com/Podcastindex-org/helipad-startos) of my repo and then submit it to the StartOS marketplace.

**Comment by daveajones** [comment]
I’ll get to that ASAP. Sorry.

**Comment by adamc199** [comment]
All good, thank you! Sideloading the new version now!

**Comment by ericpp** [comment]
Cool. Let me know how it goes and I hope you like the updates!

Sorry for the confusion around the Start OS marketplace submission. I had originally intended to submit a separate Start OS version, but though the common Docker image route was a better approach. I should probably set up a podcastindex.social account to make it easier to communicate.

**Comment by adamc199** [comment]
Install failed
![IMG_20230922_002712](https://github.com/Podcastindex-org/helipad/assets/3434034/1fbdd336-5a5a-4bae-a2e6-e10e022fded5)

**Comment by ericpp** [comment]
Hrm. Maybe I'm missing a version migration script. I think most of my testing involved uninstalling and installing rather than upgrading.

**Comment by adamc199** [comment]
I'll uninstall first

**Comment by ericpp** [comment]
I think I have a fixed version now. Uploading

**Comment by ericpp** [comment]
This one should be fixed: https://github.com/ericpp/helipad-startos/releases/tag/dev-v0.1.10.4

**Comment by adamc199** [comment]
Already installed. Working and it is now "catching up"
Has quite a way to go LOL. Will try the upgrade when it's all caught up

**Comment by ericpp** [comment]
LOL I bet. How many boosts did you have before uninstalling?

**Comment by daveajones** [comment]
> I should probably set up a podcastindex.social account to make it easier to communicate.

Email me if you need an invite.

**Comment by ericpp** [comment]
Now available! https://community-registry.start9.com/
